[package]
name = "random-id"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
radix_fmt = "1"

[[bin]]
name = "random-id"
path = "main.rs"
